services:
  redis:
      image: redis:alpine
      ports:
        - "6379:6379"

  ollama:
      build:
        context: .
        dockerfile: Dockerfile.ollama
      container_name: ollama_server
      ports:
        - "11435:11434"
      volumes:
        - ollama_data:/root/.ollama
      restart: unless-stopped

volumes:
  ollama_data: